// Code generated by ent, DO NOT EDIT.

package centralstoragepool

import (
	"time"

	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the centralstoragepool type in the database.
	Label = "central_storage_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldExt holds the string denoting the ext field in the database.
	FieldExt = "ext"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// Table holds the table name of the centralstoragepool in the database.
	Table = "central_storage_pool"
)

// Columns holds all SQL columns for centralstoragepool fields.
var Columns = []string{
	FieldID,
	FieldDeleteAt,
	FieldFilename,
	FieldExt,
	FieldSize,
	FieldPath,
	FieldHash,
	FieldCreateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "file_flow/ent/runtime"
//
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// ExtValidator is a validator for the "ext" field. It is called by the builders before save.
	ExtValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt time.Time
)
