// Code generated by ent, DO NOT EDIT.

package userstoragepool

import (
	"time"

	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the userstoragepool type in the database.
	Label = "user_storage_pool"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldExt holds the string denoting the ext field in the database.
	FieldExt = "ext"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// Table holds the table name of the userstoragepool in the database.
	Table = "user_storage_pools"
)

// Columns holds all SQL columns for userstoragepool fields.
var Columns = []string{
	FieldID,
	FieldDeleteAt,
	FieldUID,
	FieldRepoID,
	FieldParentID,
	FieldFilename,
	FieldExt,
	FieldCreateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "file_flow/ent/runtime"
//
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultParentID holds the default value on creation for the "parent_id" field.
	DefaultParentID int
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// ExtValidator is a validator for the "ext" field. It is called by the builders before save.
	ExtValidator func(string) error
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt time.Time
)
