server:
  port: 8080

db:
  driverName: postgres
  dsn: "host=127.0.0.1 port=5432 user=postgres dbname=file_flow password=Root@1998 sslmode=disable TimeZone=Asia/Shanghai"

redis:
  addr: 127.0.0.1:6379
  db: 2

jwt:
  tokenExpire: 72
  signingKey: code0451

email:
  from: mefqaq419093@163.com
  addr: smtp.163.com:465
  username: mefqaq419093@163.com
  password: TBDLMUJZQUHKAEWD
  host: smtp.163.com

minio:
  endpoint: localhost:9000
  accessKeyID: pQVJVMIAidUiyYH2
  secretAccessKey: dtTpbfJZpjuUT6KcTHWwekhUT0FxI4Xx
  useSSL: false
  bucketName: file-flow
