// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CentralStoragePoolsColumns holds the columns for the "central_storage_pools" table.
	CentralStoragePoolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "filename", Type: field.TypeString, Size: 2147483647},
		{Name: "ext", Type: field.TypeString, Size: 2147483647},
		{Name: "size", Type: field.TypeFloat64},
		{Name: "path", Type: field.TypeString, Size: 2147483647},
		{Name: "hash", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// CentralStoragePoolsTable holds the schema information for the "central_storage_pools" table.
	CentralStoragePoolsTable = &schema.Table{
		Name:       "central_storage_pools",
		Columns:    CentralStoragePoolsColumns,
		PrimaryKey: []*schema.Column{CentralStoragePoolsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "nickname", Type: field.TypeString, Size: 2147483647},
		{Name: "avatar", Type: field.TypeString, Size: 2147483647},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "password", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserStoragePoolsColumns holds the columns for the "user_storage_pools" table.
	UserStoragePoolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "uid", Type: field.TypeInt},
		{Name: "repo_id", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeInt, Default: 0},
		{Name: "filename", Type: field.TypeString, Size: 2147483647},
		{Name: "ext", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// UserStoragePoolsTable holds the schema information for the "user_storage_pools" table.
	UserStoragePoolsTable = &schema.Table{
		Name:       "user_storage_pools",
		Columns:    UserStoragePoolsColumns,
		PrimaryKey: []*schema.Column{UserStoragePoolsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CentralStoragePoolsTable,
		UsersTable,
		UserStoragePoolsTable,
	}
)

func init() {
}
