// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CentralStoragePoolColumns holds the columns for the "central_storage_pool" table.
	CentralStoragePoolColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "filename", Type: field.TypeString, Size: 2147483647},
		{Name: "ext", Type: field.TypeString, Size: 2147483647},
		{Name: "size", Type: field.TypeFloat64},
		{Name: "path", Type: field.TypeString, Size: 2147483647},
		{Name: "hash", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// CentralStoragePoolTable holds the schema information for the "central_storage_pool" table.
	CentralStoragePoolTable = &schema.Table{
		Name:       "central_storage_pool",
		Columns:    CentralStoragePoolColumns,
		PrimaryKey: []*schema.Column{CentralStoragePoolColumns[0]},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_file_id", Type: field.TypeInt},
		{Name: "expiration", Type: field.TypeInt},
		{Name: "click_number", Type: field.TypeInt},
		{Name: "create_at", Type: field.TypeTime},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "nickname", Type: field.TypeString, Size: 2147483647},
		{Name: "avatar", Type: field.TypeString, Size: 2147483647},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "password", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserStoragePoolColumns holds the columns for the "user_storage_pool" table.
	UserStoragePoolColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "uid", Type: field.TypeInt},
		{Name: "repo_id", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeInt, Default: 0},
		{Name: "filename", Type: field.TypeString, Size: 2147483647},
		{Name: "ext", Type: field.TypeString, Size: 2147483647},
		{Name: "create_at", Type: field.TypeTime},
	}
	// UserStoragePoolTable holds the schema information for the "user_storage_pool" table.
	UserStoragePoolTable = &schema.Table{
		Name:       "user_storage_pool",
		Columns:    UserStoragePoolColumns,
		PrimaryKey: []*schema.Column{UserStoragePoolColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CentralStoragePoolTable,
		SharesTable,
		UsersTable,
		UserStoragePoolTable,
	}
)

func init() {
	CentralStoragePoolTable.Annotation = &entsql.Annotation{
		Table: "central_storage_pool",
	}
	UserStoragePoolTable.Annotation = &entsql.Annotation{
		Table: "user_storage_pool",
	}
}
