// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"file_flow/ent/centralstoragepool"
	"file_flow/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CentralStoragePoolQuery is the builder for querying CentralStoragePool entities.
type CentralStoragePoolQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.CentralStoragePool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CentralStoragePoolQuery builder.
func (cspq *CentralStoragePoolQuery) Where(ps ...predicate.CentralStoragePool) *CentralStoragePoolQuery {
	cspq.predicates = append(cspq.predicates, ps...)
	return cspq
}

// Limit the number of records to be returned by this query.
func (cspq *CentralStoragePoolQuery) Limit(limit int) *CentralStoragePoolQuery {
	cspq.ctx.Limit = &limit
	return cspq
}

// Offset to start from.
func (cspq *CentralStoragePoolQuery) Offset(offset int) *CentralStoragePoolQuery {
	cspq.ctx.Offset = &offset
	return cspq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cspq *CentralStoragePoolQuery) Unique(unique bool) *CentralStoragePoolQuery {
	cspq.ctx.Unique = &unique
	return cspq
}

// Order specifies how the records should be ordered.
func (cspq *CentralStoragePoolQuery) Order(o ...OrderFunc) *CentralStoragePoolQuery {
	cspq.order = append(cspq.order, o...)
	return cspq
}

// First returns the first CentralStoragePool entity from the query.
// Returns a *NotFoundError when no CentralStoragePool was found.
func (cspq *CentralStoragePoolQuery) First(ctx context.Context) (*CentralStoragePool, error) {
	nodes, err := cspq.Limit(1).All(setContextOp(ctx, cspq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{centralstoragepool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) FirstX(ctx context.Context) *CentralStoragePool {
	node, err := cspq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CentralStoragePool ID from the query.
// Returns a *NotFoundError when no CentralStoragePool ID was found.
func (cspq *CentralStoragePoolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cspq.Limit(1).IDs(setContextOp(ctx, cspq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{centralstoragepool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) FirstIDX(ctx context.Context) int {
	id, err := cspq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CentralStoragePool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CentralStoragePool entity is found.
// Returns a *NotFoundError when no CentralStoragePool entities are found.
func (cspq *CentralStoragePoolQuery) Only(ctx context.Context) (*CentralStoragePool, error) {
	nodes, err := cspq.Limit(2).All(setContextOp(ctx, cspq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{centralstoragepool.Label}
	default:
		return nil, &NotSingularError{centralstoragepool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) OnlyX(ctx context.Context) *CentralStoragePool {
	node, err := cspq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CentralStoragePool ID in the query.
// Returns a *NotSingularError when more than one CentralStoragePool ID is found.
// Returns a *NotFoundError when no entities are found.
func (cspq *CentralStoragePoolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cspq.Limit(2).IDs(setContextOp(ctx, cspq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{centralstoragepool.Label}
	default:
		err = &NotSingularError{centralstoragepool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) OnlyIDX(ctx context.Context) int {
	id, err := cspq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CentralStoragePools.
func (cspq *CentralStoragePoolQuery) All(ctx context.Context) ([]*CentralStoragePool, error) {
	ctx = setContextOp(ctx, cspq.ctx, "All")
	if err := cspq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CentralStoragePool, *CentralStoragePoolQuery]()
	return withInterceptors[[]*CentralStoragePool](ctx, cspq, qr, cspq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) AllX(ctx context.Context) []*CentralStoragePool {
	nodes, err := cspq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CentralStoragePool IDs.
func (cspq *CentralStoragePoolQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cspq.ctx.Unique == nil && cspq.path != nil {
		cspq.Unique(true)
	}
	ctx = setContextOp(ctx, cspq.ctx, "IDs")
	if err = cspq.Select(centralstoragepool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) IDsX(ctx context.Context) []int {
	ids, err := cspq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cspq *CentralStoragePoolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cspq.ctx, "Count")
	if err := cspq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cspq, querierCount[*CentralStoragePoolQuery](), cspq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) CountX(ctx context.Context) int {
	count, err := cspq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cspq *CentralStoragePoolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cspq.ctx, "Exist")
	switch _, err := cspq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cspq *CentralStoragePoolQuery) ExistX(ctx context.Context) bool {
	exist, err := cspq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CentralStoragePoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cspq *CentralStoragePoolQuery) Clone() *CentralStoragePoolQuery {
	if cspq == nil {
		return nil
	}
	return &CentralStoragePoolQuery{
		config:     cspq.config,
		ctx:        cspq.ctx.Clone(),
		order:      append([]OrderFunc{}, cspq.order...),
		inters:     append([]Interceptor{}, cspq.inters...),
		predicates: append([]predicate.CentralStoragePool{}, cspq.predicates...),
		// clone intermediate query.
		sql:  cspq.sql.Clone(),
		path: cspq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeleteAt time.Time `json:"delete_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CentralStoragePool.Query().
//		GroupBy(centralstoragepool.FieldDeleteAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cspq *CentralStoragePoolQuery) GroupBy(field string, fields ...string) *CentralStoragePoolGroupBy {
	cspq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CentralStoragePoolGroupBy{build: cspq}
	grbuild.flds = &cspq.ctx.Fields
	grbuild.label = centralstoragepool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeleteAt time.Time `json:"delete_at,omitempty"`
//	}
//
//	client.CentralStoragePool.Query().
//		Select(centralstoragepool.FieldDeleteAt).
//		Scan(ctx, &v)
//
func (cspq *CentralStoragePoolQuery) Select(fields ...string) *CentralStoragePoolSelect {
	cspq.ctx.Fields = append(cspq.ctx.Fields, fields...)
	sbuild := &CentralStoragePoolSelect{CentralStoragePoolQuery: cspq}
	sbuild.label = centralstoragepool.Label
	sbuild.flds, sbuild.scan = &cspq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CentralStoragePoolSelect configured with the given aggregations.
func (cspq *CentralStoragePoolQuery) Aggregate(fns ...AggregateFunc) *CentralStoragePoolSelect {
	return cspq.Select().Aggregate(fns...)
}

func (cspq *CentralStoragePoolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cspq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cspq); err != nil {
				return err
			}
		}
	}
	for _, f := range cspq.ctx.Fields {
		if !centralstoragepool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cspq.path != nil {
		prev, err := cspq.path(ctx)
		if err != nil {
			return err
		}
		cspq.sql = prev
	}
	return nil
}

func (cspq *CentralStoragePoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CentralStoragePool, error) {
	var (
		nodes = []*CentralStoragePool{}
		_spec = cspq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CentralStoragePool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CentralStoragePool{config: cspq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cspq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cspq *CentralStoragePoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cspq.querySpec()
	_spec.Node.Columns = cspq.ctx.Fields
	if len(cspq.ctx.Fields) > 0 {
		_spec.Unique = cspq.ctx.Unique != nil && *cspq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cspq.driver, _spec)
}

func (cspq *CentralStoragePoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(centralstoragepool.Table, centralstoragepool.Columns, sqlgraph.NewFieldSpec(centralstoragepool.FieldID, field.TypeInt))
	_spec.From = cspq.sql
	if unique := cspq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cspq.path != nil {
		_spec.Unique = true
	}
	if fields := cspq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, centralstoragepool.FieldID)
		for i := range fields {
			if fields[i] != centralstoragepool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cspq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cspq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cspq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cspq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cspq *CentralStoragePoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cspq.driver.Dialect())
	t1 := builder.Table(centralstoragepool.Table)
	columns := cspq.ctx.Fields
	if len(columns) == 0 {
		columns = centralstoragepool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cspq.sql != nil {
		selector = cspq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cspq.ctx.Unique != nil && *cspq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cspq.predicates {
		p(selector)
	}
	for _, p := range cspq.order {
		p(selector)
	}
	if offset := cspq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cspq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CentralStoragePoolGroupBy is the group-by builder for CentralStoragePool entities.
type CentralStoragePoolGroupBy struct {
	selector
	build *CentralStoragePoolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cspgb *CentralStoragePoolGroupBy) Aggregate(fns ...AggregateFunc) *CentralStoragePoolGroupBy {
	cspgb.fns = append(cspgb.fns, fns...)
	return cspgb
}

// Scan applies the selector query and scans the result into the given value.
func (cspgb *CentralStoragePoolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cspgb.build.ctx, "GroupBy")
	if err := cspgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CentralStoragePoolQuery, *CentralStoragePoolGroupBy](ctx, cspgb.build, cspgb, cspgb.build.inters, v)
}

func (cspgb *CentralStoragePoolGroupBy) sqlScan(ctx context.Context, root *CentralStoragePoolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cspgb.fns))
	for _, fn := range cspgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cspgb.flds)+len(cspgb.fns))
		for _, f := range *cspgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cspgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cspgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CentralStoragePoolSelect is the builder for selecting fields of CentralStoragePool entities.
type CentralStoragePoolSelect struct {
	*CentralStoragePoolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (csps *CentralStoragePoolSelect) Aggregate(fns ...AggregateFunc) *CentralStoragePoolSelect {
	csps.fns = append(csps.fns, fns...)
	return csps
}

// Scan applies the selector query and scans the result into the given value.
func (csps *CentralStoragePoolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csps.ctx, "Select")
	if err := csps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CentralStoragePoolQuery, *CentralStoragePoolSelect](ctx, csps.CentralStoragePoolQuery, csps, csps.inters, v)
}

func (csps *CentralStoragePoolSelect) sqlScan(ctx context.Context, root *CentralStoragePoolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(csps.fns))
	for _, fn := range csps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*csps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
