// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"file_flow/ent/predicate"
	"file_flow/ent/share"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShareUpdate is the builder for updating Share entities.
type ShareUpdate struct {
	config
	hooks    []Hook
	mutation *ShareMutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (su *ShareUpdate) Where(ps ...predicate.Share) *ShareUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUserFileID sets the "user_file_id" field.
func (su *ShareUpdate) SetUserFileID(i int) *ShareUpdate {
	su.mutation.ResetUserFileID()
	su.mutation.SetUserFileID(i)
	return su
}

// AddUserFileID adds i to the "user_file_id" field.
func (su *ShareUpdate) AddUserFileID(i int) *ShareUpdate {
	su.mutation.AddUserFileID(i)
	return su
}

// SetExpiration sets the "expiration" field.
func (su *ShareUpdate) SetExpiration(i int) *ShareUpdate {
	su.mutation.ResetExpiration()
	su.mutation.SetExpiration(i)
	return su
}

// AddExpiration adds i to the "expiration" field.
func (su *ShareUpdate) AddExpiration(i int) *ShareUpdate {
	su.mutation.AddExpiration(i)
	return su
}

// SetClickNumber sets the "click_number" field.
func (su *ShareUpdate) SetClickNumber(i int) *ShareUpdate {
	su.mutation.ResetClickNumber()
	su.mutation.SetClickNumber(i)
	return su
}

// AddClickNumber adds i to the "click_number" field.
func (su *ShareUpdate) AddClickNumber(i int) *ShareUpdate {
	su.mutation.AddClickNumber(i)
	return su
}

// Mutation returns the ShareMutation object of the builder.
func (su *ShareUpdate) Mutation() *ShareMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ShareMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShareUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShareUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShareUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ShareUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UserFileID(); ok {
		_spec.SetField(share.FieldUserFileID, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedUserFileID(); ok {
		_spec.AddField(share.FieldUserFileID, field.TypeInt, value)
	}
	if value, ok := su.mutation.Expiration(); ok {
		_spec.SetField(share.FieldExpiration, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedExpiration(); ok {
		_spec.AddField(share.FieldExpiration, field.TypeInt, value)
	}
	if value, ok := su.mutation.ClickNumber(); ok {
		_spec.SetField(share.FieldClickNumber, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedClickNumber(); ok {
		_spec.AddField(share.FieldClickNumber, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ShareUpdateOne is the builder for updating a single Share entity.
type ShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShareMutation
}

// SetUserFileID sets the "user_file_id" field.
func (suo *ShareUpdateOne) SetUserFileID(i int) *ShareUpdateOne {
	suo.mutation.ResetUserFileID()
	suo.mutation.SetUserFileID(i)
	return suo
}

// AddUserFileID adds i to the "user_file_id" field.
func (suo *ShareUpdateOne) AddUserFileID(i int) *ShareUpdateOne {
	suo.mutation.AddUserFileID(i)
	return suo
}

// SetExpiration sets the "expiration" field.
func (suo *ShareUpdateOne) SetExpiration(i int) *ShareUpdateOne {
	suo.mutation.ResetExpiration()
	suo.mutation.SetExpiration(i)
	return suo
}

// AddExpiration adds i to the "expiration" field.
func (suo *ShareUpdateOne) AddExpiration(i int) *ShareUpdateOne {
	suo.mutation.AddExpiration(i)
	return suo
}

// SetClickNumber sets the "click_number" field.
func (suo *ShareUpdateOne) SetClickNumber(i int) *ShareUpdateOne {
	suo.mutation.ResetClickNumber()
	suo.mutation.SetClickNumber(i)
	return suo
}

// AddClickNumber adds i to the "click_number" field.
func (suo *ShareUpdateOne) AddClickNumber(i int) *ShareUpdateOne {
	suo.mutation.AddClickNumber(i)
	return suo
}

// Mutation returns the ShareMutation object of the builder.
func (suo *ShareUpdateOne) Mutation() *ShareMutation {
	return suo.mutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (suo *ShareUpdateOne) Where(ps ...predicate.Share) *ShareUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ShareUpdateOne) Select(field string, fields ...string) *ShareUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Share entity.
func (suo *ShareUpdateOne) Save(ctx context.Context) (*Share, error) {
	return withHooks[*Share, ShareMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShareUpdateOne) SaveX(ctx context.Context) *Share {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ShareUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShareUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ShareUpdateOne) sqlSave(ctx context.Context) (_node *Share, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Share.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, share.FieldID)
		for _, f := range fields {
			if !share.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != share.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UserFileID(); ok {
		_spec.SetField(share.FieldUserFileID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedUserFileID(); ok {
		_spec.AddField(share.FieldUserFileID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Expiration(); ok {
		_spec.SetField(share.FieldExpiration, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedExpiration(); ok {
		_spec.AddField(share.FieldExpiration, field.TypeInt, value)
	}
	if value, ok := suo.mutation.ClickNumber(); ok {
		_spec.SetField(share.FieldClickNumber, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedClickNumber(); ok {
		_spec.AddField(share.FieldClickNumber, field.TypeInt, value)
	}
	_node = &Share{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
