// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"file_flow/ent/predicate"
	"file_flow/ent/userstoragepool"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserStoragePoolQuery is the builder for querying UserStoragePool entities.
type UserStoragePoolQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.UserStoragePool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserStoragePoolQuery builder.
func (uspq *UserStoragePoolQuery) Where(ps ...predicate.UserStoragePool) *UserStoragePoolQuery {
	uspq.predicates = append(uspq.predicates, ps...)
	return uspq
}

// Limit the number of records to be returned by this query.
func (uspq *UserStoragePoolQuery) Limit(limit int) *UserStoragePoolQuery {
	uspq.ctx.Limit = &limit
	return uspq
}

// Offset to start from.
func (uspq *UserStoragePoolQuery) Offset(offset int) *UserStoragePoolQuery {
	uspq.ctx.Offset = &offset
	return uspq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uspq *UserStoragePoolQuery) Unique(unique bool) *UserStoragePoolQuery {
	uspq.ctx.Unique = &unique
	return uspq
}

// Order specifies how the records should be ordered.
func (uspq *UserStoragePoolQuery) Order(o ...OrderFunc) *UserStoragePoolQuery {
	uspq.order = append(uspq.order, o...)
	return uspq
}

// First returns the first UserStoragePool entity from the query.
// Returns a *NotFoundError when no UserStoragePool was found.
func (uspq *UserStoragePoolQuery) First(ctx context.Context) (*UserStoragePool, error) {
	nodes, err := uspq.Limit(1).All(setContextOp(ctx, uspq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userstoragepool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) FirstX(ctx context.Context) *UserStoragePool {
	node, err := uspq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserStoragePool ID from the query.
// Returns a *NotFoundError when no UserStoragePool ID was found.
func (uspq *UserStoragePoolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uspq.Limit(1).IDs(setContextOp(ctx, uspq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userstoragepool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) FirstIDX(ctx context.Context) int {
	id, err := uspq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserStoragePool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserStoragePool entity is found.
// Returns a *NotFoundError when no UserStoragePool entities are found.
func (uspq *UserStoragePoolQuery) Only(ctx context.Context) (*UserStoragePool, error) {
	nodes, err := uspq.Limit(2).All(setContextOp(ctx, uspq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userstoragepool.Label}
	default:
		return nil, &NotSingularError{userstoragepool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) OnlyX(ctx context.Context) *UserStoragePool {
	node, err := uspq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserStoragePool ID in the query.
// Returns a *NotSingularError when more than one UserStoragePool ID is found.
// Returns a *NotFoundError when no entities are found.
func (uspq *UserStoragePoolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uspq.Limit(2).IDs(setContextOp(ctx, uspq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userstoragepool.Label}
	default:
		err = &NotSingularError{userstoragepool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) OnlyIDX(ctx context.Context) int {
	id, err := uspq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserStoragePools.
func (uspq *UserStoragePoolQuery) All(ctx context.Context) ([]*UserStoragePool, error) {
	ctx = setContextOp(ctx, uspq.ctx, "All")
	if err := uspq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserStoragePool, *UserStoragePoolQuery]()
	return withInterceptors[[]*UserStoragePool](ctx, uspq, qr, uspq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) AllX(ctx context.Context) []*UserStoragePool {
	nodes, err := uspq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserStoragePool IDs.
func (uspq *UserStoragePoolQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uspq.ctx.Unique == nil && uspq.path != nil {
		uspq.Unique(true)
	}
	ctx = setContextOp(ctx, uspq.ctx, "IDs")
	if err = uspq.Select(userstoragepool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) IDsX(ctx context.Context) []int {
	ids, err := uspq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uspq *UserStoragePoolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uspq.ctx, "Count")
	if err := uspq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uspq, querierCount[*UserStoragePoolQuery](), uspq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) CountX(ctx context.Context) int {
	count, err := uspq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uspq *UserStoragePoolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uspq.ctx, "Exist")
	switch _, err := uspq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uspq *UserStoragePoolQuery) ExistX(ctx context.Context) bool {
	exist, err := uspq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserStoragePoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uspq *UserStoragePoolQuery) Clone() *UserStoragePoolQuery {
	if uspq == nil {
		return nil
	}
	return &UserStoragePoolQuery{
		config:     uspq.config,
		ctx:        uspq.ctx.Clone(),
		order:      append([]OrderFunc{}, uspq.order...),
		inters:     append([]Interceptor{}, uspq.inters...),
		predicates: append([]predicate.UserStoragePool{}, uspq.predicates...),
		// clone intermediate query.
		sql:  uspq.sql.Clone(),
		path: uspq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeleteAt time.Time `json:"delete_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserStoragePool.Query().
//		GroupBy(userstoragepool.FieldDeleteAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uspq *UserStoragePoolQuery) GroupBy(field string, fields ...string) *UserStoragePoolGroupBy {
	uspq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserStoragePoolGroupBy{build: uspq}
	grbuild.flds = &uspq.ctx.Fields
	grbuild.label = userstoragepool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeleteAt time.Time `json:"delete_at,omitempty"`
//	}
//
//	client.UserStoragePool.Query().
//		Select(userstoragepool.FieldDeleteAt).
//		Scan(ctx, &v)
//
func (uspq *UserStoragePoolQuery) Select(fields ...string) *UserStoragePoolSelect {
	uspq.ctx.Fields = append(uspq.ctx.Fields, fields...)
	sbuild := &UserStoragePoolSelect{UserStoragePoolQuery: uspq}
	sbuild.label = userstoragepool.Label
	sbuild.flds, sbuild.scan = &uspq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserStoragePoolSelect configured with the given aggregations.
func (uspq *UserStoragePoolQuery) Aggregate(fns ...AggregateFunc) *UserStoragePoolSelect {
	return uspq.Select().Aggregate(fns...)
}

func (uspq *UserStoragePoolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uspq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uspq); err != nil {
				return err
			}
		}
	}
	for _, f := range uspq.ctx.Fields {
		if !userstoragepool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uspq.path != nil {
		prev, err := uspq.path(ctx)
		if err != nil {
			return err
		}
		uspq.sql = prev
	}
	return nil
}

func (uspq *UserStoragePoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserStoragePool, error) {
	var (
		nodes = []*UserStoragePool{}
		_spec = uspq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserStoragePool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserStoragePool{config: uspq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uspq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uspq *UserStoragePoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uspq.querySpec()
	_spec.Node.Columns = uspq.ctx.Fields
	if len(uspq.ctx.Fields) > 0 {
		_spec.Unique = uspq.ctx.Unique != nil && *uspq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uspq.driver, _spec)
}

func (uspq *UserStoragePoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userstoragepool.Table, userstoragepool.Columns, sqlgraph.NewFieldSpec(userstoragepool.FieldID, field.TypeInt))
	_spec.From = uspq.sql
	if unique := uspq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uspq.path != nil {
		_spec.Unique = true
	}
	if fields := uspq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstoragepool.FieldID)
		for i := range fields {
			if fields[i] != userstoragepool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uspq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uspq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uspq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uspq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uspq *UserStoragePoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uspq.driver.Dialect())
	t1 := builder.Table(userstoragepool.Table)
	columns := uspq.ctx.Fields
	if len(columns) == 0 {
		columns = userstoragepool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uspq.sql != nil {
		selector = uspq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uspq.ctx.Unique != nil && *uspq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uspq.predicates {
		p(selector)
	}
	for _, p := range uspq.order {
		p(selector)
	}
	if offset := uspq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uspq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserStoragePoolGroupBy is the group-by builder for UserStoragePool entities.
type UserStoragePoolGroupBy struct {
	selector
	build *UserStoragePoolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uspgb *UserStoragePoolGroupBy) Aggregate(fns ...AggregateFunc) *UserStoragePoolGroupBy {
	uspgb.fns = append(uspgb.fns, fns...)
	return uspgb
}

// Scan applies the selector query and scans the result into the given value.
func (uspgb *UserStoragePoolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uspgb.build.ctx, "GroupBy")
	if err := uspgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserStoragePoolQuery, *UserStoragePoolGroupBy](ctx, uspgb.build, uspgb, uspgb.build.inters, v)
}

func (uspgb *UserStoragePoolGroupBy) sqlScan(ctx context.Context, root *UserStoragePoolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uspgb.fns))
	for _, fn := range uspgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uspgb.flds)+len(uspgb.fns))
		for _, f := range *uspgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uspgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uspgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserStoragePoolSelect is the builder for selecting fields of UserStoragePool entities.
type UserStoragePoolSelect struct {
	*UserStoragePoolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (usps *UserStoragePoolSelect) Aggregate(fns ...AggregateFunc) *UserStoragePoolSelect {
	usps.fns = append(usps.fns, fns...)
	return usps
}

// Scan applies the selector query and scans the result into the given value.
func (usps *UserStoragePoolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, usps.ctx, "Select")
	if err := usps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserStoragePoolQuery, *UserStoragePoolSelect](ctx, usps.UserStoragePoolQuery, usps, usps.inters, v)
}

func (usps *UserStoragePoolSelect) sqlScan(ctx context.Context, root *UserStoragePoolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(usps.fns))
	for _, fn := range usps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*usps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
