// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CentralStoragePool is the predicate function for centralstoragepool builders.
type CentralStoragePool func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
